title: Collation Editor Core
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search_enabled: true
sidebar:
  - introduction
  - installation
  - label: Services File
    children:
       - required-variables
       - required-functions
       - optional-variables
       - optional-functions
  - python-services
  - project-settings
  # - label: Installation
  #   children:
  #     - initialisation
  #     - services file
  # - label: Configuration
  #   children:
  #     - Your own data