name: Collation Editor Core
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
search-enabled: true
sidebar:
  - introduction
  # - label: Installation
  #   children:
  #     - initialisation
  #     - services file
  # - label: Configuration
  #   children:
  #     - Your own data