name: linting

on: [push]

jobs:
  ruff:
    permisions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: |
        pip install ruff
    - name: Run ruff
      run: |
        ruff check .
        ruff format --check --diff .

  eslint:
    permisions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies and lint
        run: |
          npm i eslint 
          npm i @stylistic/eslint-plugin
          node_modules/eslint/bin/eslint.js static/CE_core/js/*.js --ignore-pattern "**/*.min.js"

  stylelint:
    permisions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies and lint
        run: |
          npm i eslint 
          npm i @stylistic/eslint-plugin
          node_modules/stylelint/bin/stylelint.mjs static/CE_core/css/*.css
